export function WebsiteTermsOfUse() {
  return (
    <div className="text-base max-w-7xl mx-auto px-6 my-4 md:px-10 lg:px-6 text-[#333333]">
      <div className="text-xl font-semibold underline">
        <h1>Last Minute Wellness Inc.’s Website Terms of Use</h1>
      </div>
      <div className="space-y-4">
        <p>The Last Minute Wellness website, together with any of its affiliated mobile applications or communication platforms related to this website (collectively, the “<strong>Website</strong>”), is operated by Last Minute Wellness Inc. Throughout the Website and in these terms and conditions, the terms “we”, “us”, “our”, and “Last Minute Wellness” refer to Last Minute Wellness Inc., its affiliates and each of their respective employees, officers, directors and representatives.  Last Minute Wellness offers this Website, including all information, tools and services available from this Website to “you”, the “user” or “Client” conditioned upon your acceptance of all terms, conditions, policies and notices stated here </p>
        <p>By using our Website or purchasing any of Last Minute Wellness’s goods or services, you expressly agree to engage in our Website’s <strong>“Service”</strong> and agree to be bound by the Website’s terms and conditions (<strong>“Terms of Use”</strong>, or <strong>“Terms”</strong>), including those additional terms and conditions and policies referenced herein and/or made available on the Website from time to time. These Terms of Use apply to all users of the Website, including without limitation users who are browsers, vendors, customers, merchants, clients, and/ or contributors of content.</p>
        <p>PLEASE READ THESE TERMS OF USE CAREFULLY. IF YOU DO NOT AGREE WITH THE TERMS OF USE, DO NOT USE OR VISIT ANY PORTION OF THE WEBSITE. BY USING OR VISITING THE WEBSITE, YOU AGREE TO THE TERMS OF USE, AS WELL AS THE TERMS & CONDITIONS OF ANY THIRD-PARTY HOSTING PROVIDERS OR SERVICE PARTNERS.  NOTWITHSTANDING THE FOREGOING, LAST MINUTE WELLNESS DISCLAIMS ANY RESPONSIBILITY OR LIABILITY FOR ANY CLAIMS ARISING DIRECTLY FROM THE USE OF THIRD-PARTY HOSTING PROVIDERS OR SERVICE PARTNERS. IF THESE TERMS OF USE ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO THESE TERMS OF USE.</p>
        <p>The Website and the information contained therein (including changes to these Terms of Use) may be changed or updated from time to time without notice.  It is your responsibility to check for such changes.  Last Minute Wellness may revise, supplement or delete any video content, audio content, written or graphical materials, information, the resources contained in the Website, and any products or services rendered through the Website or affiliated apps by Last Minute Wellness on the Website (collectively, the <strong>“Content”</strong>), and reserves the right to make such changes to the Content without prior notification to past, current or prospective visitors. Any new features or tools which are added to the current Website shall also be subject to the Terms of Use. You can review the most current version of the Terms of Use at any time on this page. We reserve the right to update, change or replace any part of these Terms of Use by posting updates and/or changes to our Website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Website following the posting of any changes constitutes acceptance of those changes.</p>
        <p>Although Last Minute Wellness believes this information to be correct at the time it is posted, Last Minute Wellness does not warrant the accuracy, completeness or currency, or fitness for any purpose whatsoever, of this Content at all times and Last Minute Wellness cannot guarantee or accept any responsibility or liability for the accuracy, currency or completeness, or fitness for any purpose whatsoever, of the Content.  Last Minute Wellness neither warrants nor represents that your use of Content will not infringe rights of third parties not owned by or affiliated with Last Minute Wellness.</p>
        <p>You may not interfere with the security of, or otherwise abuse, the Website or any system resources, services or networks connected to, or accessible through, the Website. You may only use the Website for lawful purposes.</p>
        <div>
          <h5 className="font-semibold mt-2">Limited License</h5>
          <p>Subject to these Terms of Use, you are granted a limited license only to display the Content contained in the Website for your own personal, non-commercial use, provided that such Content are not modified and that copyright and other intellectual property notices are not altered or deleted.  You may not create derivative works from or otherwise reproduce, modify, republish or disseminate any Content contained in the Website in any manner or form whatsoever. Any other use of such materials or information without Last Minute Wellness’s written permission is prohibited, and all title, trademarks and copyrights to the Content are owned by Last Minute Wellness.  You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Content, the Website’s Service, or use of the Service, without the express prior written permission by Last Minute Wellness.  We reserve the right to refuse the provision of any goods or services, or to restrict usage of this Website, to anyone for any reason at any time.</p>
        </div>

        <div>
          <h5 className="font-semibold mt-2">Content that you share with us.</h5>
          <p>The Website may contain features that allow you to share your personal information with us (including, without limitation, full name, address, email address, telephone number, setting preferences, date of birth, gender, health and medication history, personal information regarding any caregivers or delegated individuals who are authorized to order goods and services on the Website for and on behalf of another individual, and any other personal information you provide to us, including any text, pictures or other content, account details (username, password stored in encrypted form), information for transactions with us and/or a third party through the Website, statistical data about your usage of the Website, information provided in connection with products and services, and your payment information (for example, credit card information), and any other demographic information).   By doing so, you consent that we may use such information for the purposes of the Content that it was provided to us. You also represent and warrant that you have all rights necessary to share the information with us, and that any information you provide to the Website is free from viruses and other malware.  </p>
          <p>We do not solicit or encourage submissions of Content containing ideas or suggestions relating to the Website, the Service, or Last Minute Wellness’s business.  If you send us any ideas or suggestions, regardless of the topic, we will have no obligations with respect to such ideas or suggestions and may use them for any purpose whatsoever.  You agree that Last Minute Wellness shall be the copyright owner of all copyrightable works of every kind and description of any Content which contains your information, except where you notify Last Minute Wellness of your claimed rights to copyright of that information in writing.  You understand that any Content you submit to the Website (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p>
          <p>You acknowledge that the Internet is not a fully secure medium and any communication may be lost, intercepted or altered.  Last Minute Wellness is not liable for any damages related to communications to, or from, the Website.  You agree with respect to any information provided by you to us through the Website or via e-mail that: a) Last Minute Wellness has no obligation concerning such information; b) the information is non-confidential; c) Last Minute Wellness may use, disclose, distribute or copy the information and may use any ideas, concepts or know-how contained in the information for any purpose; and d) the information is truthful and disclosure of the information does not violate the legal rights of others.</p>
        </div>

        <div>
          <h5 className="font-semibold mt-2">Proprietary Rights.</h5>
          <p>The Content contained on the Website is protected under the laws of Canada and of other countries.  Certain words, phrases, names, titles, icons, graphics, designs or logos used on the Website may constitute trademarks, service marks or trade names of Last Minute Wellness or other entities.  The display of trademarks, service marks or trade names on the pages of the Website does not imply that a license of any kind has been granted to anyone else.  Except as specifically set out herein, you may not use any such trademarks, service marks or trade names in any manner whatsoever.</p>
          <p>Images of people or places displayed on the Website are either the property of, or used with permission by, Last Minute Wellness (for example, customer and service provider personal photographs that they have submitted to the Website). The use of these images by you, or anyone else authorized by you, is prohibited unless specifically permitted by these Terms of Use or specific permission provided elsewhere on the Website. Any unauthorized use of the images may violate copyright laws, trademark laws, the laws of privacy and publicity and communications regulations and statutes.</p>
        </div>
        <div>
          <h5 className="font-semibold mt-2">Disclaimer of all Warranties – Exclusion of Liability</h5>
          <p>THE WEBSITE MAY FROM TIME TO TIME CONTAIN INFORMATION RELATING TO VARIOUS TYPES OF PERSONAL INFORMATION OR MEDICAL OR HEALTH INFORMATION. THE CONTENT, MATERIALS AND INFORMATION CONTAINED ON THE WEBSITE ARE PROVIDED FOR INFORMATION PURPOSES ONLY AND ARE NOT INTENDED TO SUBSTITUTE THE ADVICE PROVIDED BY MEDICAL PROFESSIONAL.</p>
          <p>ALL USE OF THE CONTENT ON THIS WEBSITE IS ON A STRICTLY AS-IS, WHERE-IS BASIS AND YOU AGREE THAT ANY USE OF THE CONTENT IS AT YOUR OWN RISK.  </p>
          <p>THE WEBSITE, AND ALL MATERIALS AND INFORMATION CONTAINED THEREIN, ARE PROVIDED "AS IS", "AS AVAILABLE", AND "WITH ALL FAULTS" AND ARE USED BY YOU AT YOUR SOLE RISK.  LAST MINUTE WELLNESS MAKES NO EXPRESS OR IMPLIED WARRANTIES, CONDITIONS OR REPRESENTATIONS WHATSOEVER, INCLUDING THOSE IMPLIED BY STATUTE OR LAW, AND SPECIFICALLY DISCLAIMS THE SAME INCLUDING WITHOUT LIMITATION, ANY WARRANTIES, REPRESENTATIONS OR CONDITIONS OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. LAST MINUTE WELLNESS HEREBY EXPRESSLY DISCLAIMS ANY LIABILITY FOR ERRORS OR OMISSIONS IN THE INFORMATION CONTAINED IN THE WEBSITE.</p>
          <p>IN ADDITION, WITHOUT LIMITING THE FOREGOING, LAST MINUTE WELLNESS DOES NOT REPRESENT OR WARRANT THAT THE WEBSITE OR THE MATERIALS OR INFORMATION CONTAINED THEREIN WILL MEET YOUR REQUIREMENTS OR THAT THEIR USE WILL BE UNINTERRUPTED OR ERROR-FREE.  THE WEBSITE MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS.  LAST MINUTE WELLNESS ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY SUCH BUGS, ERRORS, PROBLEMS OR LIMITATIONS IN THE OPERATION OF, OR ANY INFORMATION OR MATERIALS CONTAINED IN, THE WEBSITE.</p>
          <p>AS ABOVE, YOU ASSUME ALL RESPONSIBILITY AND RISK FOR USE OF THE WEBSITE, INCLUDING WITHOUT LIMITATION ANY OF THE MATERIALS OR INFORMATION CONTAINED THEREIN.</p>
          <p>TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL LAST MINUTE WELLNESS OR ANY OF ITS AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, EQUITYHOLDERS, PARTNERS OR AGENTS BE LIABLE FOR ANY INCIDENTAL, INDIRECT, PUNITIVE, EXEMPLARY, CONSEQUENTIAL OR OTHER SIMILAR DAMAGES WHATSOEVER, OR ANY DAMAGES FOR LOSS OF PROFITS, INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR LOSS OF OPPORTUNITY IN CONNECTION WITH ANY CLAIM, LOSS, DAMAGE, ACTION, SUIT OR OTHER PROCEEDING ARISING UNDER OR OUT OF THESE TERMS OF USE, INCLUDING WITHOUT LIMITATION IN CONNECTION WITH OR ARISING FROM YOUR USE OF, RELIANCE UPON, ACCESS TO, OR EXPLOITATION OF THE WEBSITE OR WITH ANY LINKED THIRD-PARTY WEBSITE, THE MATERIALS OR INFORMATION CONTAINED THEREIN, OR ANY PART THEREOF, OR ANY RIGHTS GRANTED TO YOU HEREUNDER, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHETHER THE ACTION IS BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OR OTHERWISE. </p>
          <p>IN EVERY EVENT, BY USING OUR WEBSITE, YOU AGREE THAT LAST MINUTE WELLNESS’S TOTAL MAXIMUM AGGREGATE LIABILITY TO YOU UNDER THESE TERMS OF USE OR THE USE OR EXPLOITATION OF ANY OR ALL PART OF THE WEBSITE, THE INFORMATION OR THE MATERIALS CONTAINED THEREIN, IN ANY MANNER WHATSOEVER SHALL BE LIMITED TO TWENTY ($20.00) DOLLARS.  </p>
          <p>THE CONSIDERATION BEING PAID HEREUNDER DOES NOT INCLUDE ANY CONSIDERATION FOR LAST MINUTE WELLNESS TO ASSUME ANY RISKS BEYOND THOSE EXPRESSLY ASSUMED HEREIN AND IF ANY SUCH RISKS WERE TO BE ASSUMED BY LAST MINUTE WELLNESS, LAST MINUTE WELLNESS WOULD NOT HAVE ENTERED INTO THIS AGREEMENT WITHOUT CHARGING SUBSTANTIAL FEES. </p>
          <p>SOME JURISDICTIONS DO NOT ALLOW FOR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
          <p>YOU AGREE TO INDEMNIFY AND HOLD LAST MINUTE WELLNESS AND ITS OFFICERS, DIRECTORS, EQUITYHOLDERS, PREDECESSORS, SUCCESSORS, ASSIGNS, EMPLOYEES, AND AGENTS HARMLESS AGAINST ALL CLAIMS OR LIABILITY ASSERTED AGAINST LAST MINUTE WELLNESS ARISING OUT OF OR IN CONNECTION WITH ANY BREACH BY YOU OR ANYONE ACTING ON YOUR BEHALF OF ANY OF THESE TERMS OF USE.</p>
        </div>
        <div>
          <h5 className="font-semibold mt-2">Code of Conduct.</h5>
          <p>You may not interfere with the security of, or otherwise abuse, the Website, or any system resources, services or networks connected to or accessible through the Website.  You may only use the Website for lawful purposes. You agree that you will not attempt to, nor permit any third party to, enter restricted areas of Last Minute Wellness’s computer systems or perform functions that you are not authorized to perform pursuant to these Terms of Use.  </p>
          <p>While using the Website, you agree to comply with all applicable laws, rules and regulations.  </p>
          <p>You further agree not to: a) mirror or frame any part of the Website without Last Minute Wellness’s express prior written consent; or b) use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, "scrape," "data mine" or in any way reproduce or circumvent the navigational structure or presentation of the Website, without our express prior written consent. </p>
          <p>We reserve the right, in our sole discretion, to take any actions we deem necessary and appropriate to preserve the integrity of the Website.</p>
          <p>Last Minute Wellness may, without notice, temporarily suspend your, or any other party's, access to the Website if we reasonably suspect that you, or any other parties, are obtaining unauthorized access to our other systems or information, or are using otherwise valid user identifications or passwords in any other unauthorized manner. These suspensions will be for such periods of time as Last Minute Wellness may reasonably determine is necessary to permit the thorough investigation of such suspended activity.</p>
          <p>Although Last Minute Wellness may from time to time monitor or review discussions, ratings, feedback, chats, postings, transmissions, and the like on the Website, Last Minute Wellness is under no obligation to do so and assumes no responsibility or liability arising from the content of any part of the Website, nor for any error, defamation, libel, slander, omission, falsehood, obscenity, pornography, profanity, danger or inaccuracy contained in any information within such locations on the Website. You are prohibited from posting or transmitting any unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic or profane material or any material that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability or otherwise violate any law. Last Minute Wellness will fully cooperate with any law enforcement authorities or court order requesting or directing Last Minute Wellness to disclose the identity of anyone posting any such information or materials.</p>
        </div>
        <div>
          <h5 className="font-semibold mt-2">Links to Third Party Websites</h5>
          <p>Last Minute Wellness does not control any third-party website, and is therefore not responsible for the content of any linked website or any link contained in a linked website. Linked websites are not part of the Website. Last Minute Wellness provides such links only as a convenience and the inclusion of any link does not imply endorsement, investigation or verification by Last Minute Wellness of the linked website or information contained therein and Last Minute Wellness does not make any representations regarding the privacy practices, content or accuracy of materials on such third-party sites.</p>
        </div>
        <div>
          <h5 className="font-semibold mt-2">Internet Software or Computer Viruses</h5>
          <p>Due to technical difficulties with the Internet, Internet software or transmission problems could produce inaccurate or incomplete copies of information or materials contained on the Website.  Computer viruses or other destructive programs may also be inadvertently downloaded from the Website.</p>
          <p>Last Minute Wellness shall not be responsible or liable for any software, computer viruses or other destructive, harmful or disruptive files or programs that may infect or otherwise impact your use of your computer, tablet or smartphone device or other property on account of your access to, use of, or browsing on the Website or your downloading of any of the information or materials from the Website.  Last Minute Wellness recommends that you install appropriate anti-virus or other protective software.</p>
        </div>
        <div>
          <h5 className="font-semibold mt-2">Miscellaneous</h5>
          <p>Last Minute Wellness is formed in the Province of Alberta, Canada, and the Website is controlled, operated and administered by Last Minute Wellness from the Province of Alberta, Canada. The Website can be accessed from all areas of Canada, the United States as well as from other countries around the world. As each of these jurisdictions has laws that may differ from those of Canada, by accessing the Website, you acknowledge and agree that, except where prohibited by law, all matters relating to these Terms of Use and access to, or use of, the Website (including any of the materials or information contained therein), and the resolution of any dispute arising between the parties shall be governed and construed in accordance with the laws of the Province of Alberta (without reference to conflicts of laws principles).  Except where prohibited by law, you agree that any legal action or proceeding between you and Last Minute Wellness which in any way concerns these Terms of Use or the use of the Website or any materials or information contained therein shall be brought exclusively in the courts in the Province of Alberta sitting in Calgary, and these Terms of Uses shall be treated as an Alberta contract and the laws of Alberta shall govern, without regard to any conflict of laws principles that may apply.  Except where prohibited by applicable law, you agree to waive any right you may have to commence or participate in any class action against Last Minute Wellness relating to any such dispute and you also agree to opt out of any class proceedings against Last Minute Wellness.  Notwithstanding the foregoing, either party may apply to any court of competent jurisdiction to obtain injunctive or other emergency or similar relief. </p>
          <p>Last Minute Wellness makes no representation that access to the Website or that the information contained therein is appropriate or legal in all jurisdictions.  You may not access the Website or use any information in those jurisdictions where it would be illegal.  In any case, your access to the Website is entirely at your own initiative and you are responsible for ensuring that all laws are complied with.</p>
          <p>Last Minute Wellness’s failure to insist upon or enforce strict performance of any provision of these Terms of Use shall not be construed as a waiver of any provision or right.</p>
          <p>If any provision or part thereof of these Terms of Use is wholly or partially unenforceable, the parties or, in the event the parties are unable to agree, a court of competent jurisdiction, shall put in place thereof an enforceable provision or provisions, or part thereof, that as nearly as possible reflects the terms of the unenforceable provision or part thereof.</p>
          <p>The provisions of this Term of Service shall survive any termination, expiry, or subsequent amendment of these Terms of Use.</p>
        </div>
      </div>
    </div>
  );
}
